services:
  backend:
    build:
      context: ./video-downloader-back
      dockerfile: Dockerfile
    container_name: downloadit-backend
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - FEEDBACK_EMAIL=${FEEDBACK_EMAIL}
